inveniosoftware/invenio-webhooks

CHANGES.rst, RELEASE-NOTES.rst, invenio_webhooks/version.py
=> Invenio-Webhooks v0.1.0

.travis.yml, CHANGES.rst, RELEASE-NOTES.rst, invenio_webhooks/version.py
=> release: v1.0.0a1

invenio_webhooks/version.py
=> version: post-release bump

invenio_webhooks/models.py
=> global: fix missing tablename

invenio_webhooks/ext.py
=> ext: entry point loading fix

CHANGES.rst, RELEASE-NOTES.rst, docs/conf.py, invenio_webhooks/version.py, setup.py, tests/conftest.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> release: v1.0.0a2

CHANGES.rst, RELEASE-NOTES.rst, invenio_webhooks/version.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> release: v1.0.0a3

setup.py
=> global: compatibility fix with Flask-WTF>=0.13

CHANGES.rst, RELEASE-NOTES.rst, invenio_webhooks/version.py
=> release: v1.0.0a4

invenio_webhooks/errors.py, invenio_webhooks/models.py, invenio_webhooks/views.py, tests/test_api.py, tests/test_receivers.py
=> api: REST for events

invenio_webhooks/errors.py, invenio_webhooks/models.py, invenio_webhooks/views.py, tests/conftest.py, tests/test_api.py, tests/test_receivers.py
=> api: simple status code extraction

invenio_webhooks/models.py
* Fixes improper Celery status response through the Event API.
(closes #40)
Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>
=> models: Celery status response from event API

invenio_webhooks/models.py, tests/test_receivers.py
* Changes exception to NotImplementedError in run method.  (closes #44)
=> models: NotImplementedError in default run method

invenio_webhooks/views.py, tests/test_api.py
* Takes the user id either from a provided access token or
the current user.
=> global: token or current_user id

AUTHORS.rst
- Adds myself to AUTHORS file.
Signed-off-by: Orestis Melkonian melkon.or@gmail.com
=> global: update AUTHORS

.travis.yml, invenio_webhooks/_compat.py, invenio_webhooks/models.py, invenio_webhooks/views.py, setup.py, tests/conftest.py
* remove reference to _cached_json Flask Request private attribute
because its location has been changed with Flask 1.0 and the `delattr`
command was failing
=> global: remove reference to Flask internals

CHANGES.rst, invenio_webhooks/__init__.py
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> release: v1.0.0

.github/workflows/pypi-publish.yml
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> release-fix: v1.0.0

README.rst, invenio_webhooks/models.py, invenio_webhooks/views.py, setup.cfg
I took the opportunity and also changed the license to MIT 
closes https://github.com/inveniosoftware/invenio-webhooks/issues/69
closes https://github.com/inveniosoftware/invenio-webhooks/issues/61
=> views: improved error handling

CHANGES.rst, invenio_webhooks/__init__.py
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> release: v1.0.1
